/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sell.java
 *
 * Created on Sep 24, 2014, 2:23:30 PM
 */

package MedicalStore;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author SONY
 */
public class Sell extends javax.swing.JFrame {

    /** Creates new form Sell */
    public Sell() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        na = new javax.swing.JTextField();
        ge = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setText("UPDATE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 10, 120, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setText("TAB. QUANTITY");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 150, 150, 30);
        getContentPane().add(pi);
        pi.setBounds(570, 60, 150, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel3.setText("TAB. NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 100, 150, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel7.setText("TAB. ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 60, 150, 30);
        getContentPane().add(na);
        na.setBounds(570, 100, 150, 30);
        getContentPane().add(ge);
        ge.setBounds(570, 150, 150, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 210, 100, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jButton2.setText("UPDATE QUANTITY");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(560, 210, 161, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalStore/img.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 20, 410, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     String id2=pi.getText();
     String nam=na.getText();
     String quan=ge.getText();

     try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tablets","root","");

    //     String query1 = "select quantity - '"+quan+"' where id='"+id2+"'";

          String query = "update tabs set quantity = '"+quan+"' where id='"+id2+"'";
           Statement smt3=con.createStatement();
         //ResultSet   rs=smt3.executeQueryUpdate(query);



                       int success=smt3.executeUpdate(query);
                            if(success==1)
                            {
                                JOptionPane.showMessageDialog(this, "DETAILS Successfully Added ");
                               //emp1.showMessageDialog(this, "Problem in Saving. Retry");
                            }
                            else
                            {

                                JOptionPane.showMessageDialog(this, "Problem in Saving. Retry");
                            }


        }

    catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.setVisible(false);
     mainFrame d=new mainFrame();
     d.setVisible(true);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ge;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField na;
    private javax.swing.JTextField pi;
    // End of variables declaration//GEN-END:variables

}
